services:
  app:
    image: node:18-alpine
    build:
      context: ../.
      dockerfile: containerization/Dockerfile
    command:
      - sh
      - -c
      - "yarn install && yarn run dev"
    ports:
      - 127.0.0.1:${HOST_PORT}:3000
    working_dir: /app/
    volumes:
      - ../.:/app
    env_file:
      - ../.env.app
    depends_on:
      mysql:
        condition: service_started

  mysql:
    image: mysql:8.0
    volumes:
      - todo-mysql-data:/var/lib/mysql
    env_file: ../.env.db
      #    healthcheck:
      #      test: [ "CMD", "mysql", "--execute", "SHOW DATABASES;" ]
      #      interval: 3s
      #      retries: 5
      #      timeout: 5s
      #      start_period: 15s


volumes:
  todo-mysql-data:
